# Generated by Django 4.2.4 on 2023-08-21 12:35

from django.db import migrations

def populate_models(apps, schema_editor):
    User = apps.get_model('users', 'User')

    user1 = User.objects.create(username='user10', password='password123')
    user2 = User.objects.create(username='user20', password='password123')
    user3 = User.objects.create(username='user30', password='password123')
    user4 = User.objects.create(username='user40', password='password123')

    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')

    c1 = Category.objects.create(name='Аксессуары')
    c2 = Category.objects.create(name='Средства гигиены')
    c3 = Category.objects.create(name='Косметика')
    c4 = Category.objects.create(name='Одежда')
    c5 = Category.objects.create(name='Обувь')

    p1 = Product.objects.create(name='Сумка', serial_number='A1234', description='Бежевая сумка.', user=user1)
    p2 = Product.objects.create(name='Шампунь', serial_number='H1234', description='Шампунь для волос 2в1.', user=user2)
    p3 = Product.objects.create(name='Губная помада', serial_number='COS1234', description='Красная помада.', user=user1)
    p4 = Product.objects.create(name='Толстовка с замком', serial_number='CL1234', description='Красивая толстовка.', user=user3)
    p5 = Product.objects.create(name='Летние кроссовки', serial_number='S1234', description='Яркие кроссовки.', user=user4)

    FavouriteProduct = apps.get_model('products', 'FavouriteProduct')

    fp1 = FavouriteProduct.objects.create(user=user1, product=p3)
    fp2 = FavouriteProduct.objects.create(user=user4, product=p2)
    fp3 = FavouriteProduct.objects.create(user=user2, product=p1)

    ProductImage = apps.get_model('products', 'ProductImage')

    pi1 = ProductImage.objects.create(product=p1, image='django-api/media/hangbag.jpg')
    pi2 = ProductImage.objects.create(product=p2, image='django-api/media/shampoo.jpg')
    pi3 = ProductImage.objects.create(product=p3, image='django-api/media/lipstick.jpg')
    pi4 = ProductImage.objects.create(product=p4, image='django-api/media/tolstovka.jpg')
    pi5 = ProductImage.objects.create(product=p5, image='django-api/media/shoes.jpg')



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_updated_at_and_more'),
        ('users', '0001_initial')
    ]

    # operations = [
    #     migrations.RunPython(populate_models),
    # ]
