# Generated by Django 4.2.4 on 2023-08-21 18:10

from django.db import migrations

def models_population(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    # Create 10 Category instances
    for i in range(1, 11):
        Category.objects.create(name=f'Category {i}')

    Compound = apps.get_model('products', 'Compound')
    # Create 10 Compound instances
    for i in range(1, 11):
        Compound.objects.create(name=f'Compound {i}')

    User = apps.get_model('users', 'User')
    # Create a User instance (assuming you have set up the User model)
    user = User.objects.create(username='test_user', password='test_password')

    Product = apps.get_model('products', 'Product')
    # Create 10 Product instances
    for i in range(1, 11):
        product = Product.objects.create(
            name=f'Product {i}',
            serial_number=f'PR{i}',
            description=f'This is description for Product {i}',
            way_to_use=f'How to use Product {i}: ...',
            user=user
        )
        product.categories.set(Category.objects.all())
        product.compound.set(Compound.objects.all())

    FavouriteProduct = apps.get_model('products', 'FavouriteProduct')
    # Create 10 FavouriteProduct instances for the user and products
    for product in Product.objects.all():
        FavouriteProduct.objects.create(user=user, product=product)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_compound_product_way_to_use_product_compound'),
        ('users', '0001_initial')
    ]

    # operations = [
    #     migrations.RunPython(models_population),
    # ]
