version: "3"
services:
  postgres:
    image: postgres:latest
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: ./django-api/.env
    restart: always

  api:
    entrypoint: /entrypoint.sh
    container_name: djangoapp
    build:
      context: ./django-api
    ports:
      - "8002:8002"  # Проброс порта для бэкенда
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./:/react-docker:delegated
#      - /node_modules
    ports:
      - "8082:8082"  # Проброс порта для фронтенда
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
